import Foter from "@/components/static/Foter";
import React from 'react'
import "./globals.css";
export const metadata = {
  title: "TieBreaker",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Foter />
      </body>
    </html>
  );
}
