"use client";
import Foter from "@/components/static/Foter";
import React, { useEffect } from "react";
import "./globals.css";
import { AnimatePresence } from "framer-motion";
import { initIntercom, shutdownIntercom } from "../utils/intercom"; // Adjust the path based on your utils location
import * as amplitude from "@amplitude/analytics-node";
import { Toaster } from "@/components/ui/toaster";

/*
export const metadata = {
  title: "TieBreaker",
  description: "Generated by Next.js",
};
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    // Initialize Intercom when the app mounts
    initIntercom();

    // Cleanup Intercom when the app unmounts
    return () => {
      shutdownIntercom();
    };
  }, []);

  amplitude.init("b770130e4c71a5a4fa0667e2dd19e316", {
    serverZone: amplitude.Types.ServerZone.EU,
  });

  return (
    <html lang="en">
      <body>
        <Toaster />
        <AnimatePresence mode="wait">{children}</AnimatePresence>
        <Foter />
      </body>
    </html>
  );
}
