import Footer from "@/components/static/Foter"; // Ensure this is correctly spelled as 'Footer'
import React from "react";
import "./globals.css";
import { AuthProvider } from "./context/AppContext"; // Import the AuthProvider

export const metadata = {
  title: "TieBreaker",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("Rendering RootLayout...");
  return (
    <html lang="en">
      <body>
        {/* Wrap the children with AuthProvider to provide context to the entire app */}
        <AuthProvider>
          {children}  {/* Children will have access to the AuthContext */}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}