"use client"; // Mark this component as a Client Component (Unchanged)

import React from "react"; // React import is retained (Unchanged)
import SignupForm from "@/components/signup/SignupForm"; // SignupForm import is retained (Unchanged)
import SectionTitle from "@/components/static/SectionTitle"; // SectionTitle import is retained (Unchanged)
import AuthLink from "@/components/static/AuthLink"; // AuthLink import is retained (Unchanged)

// Removed session handling logic (Unchanged) 

// Removed the import of Logo and Button (Unchanged)
// import { Input } from "@/components/ui/input"; (Removed)
// import Logo from "@/components/static/Logo"; (Removed)
// import { Button } from "@/components/ui/button"; (Removed)

/*export const metadata = { // Added metadata for the page title and description
  title: "TieBreaker | signup",
  description: "Generated by Next.js",
};*/

const Signup = () => {
  return (
    <div>
      <SectionTitle classname="mt-20 mb-5" text="Sign up, Let's eat!" />
      {/* SectionTitle is used to display the title of the page */}
      <SignupForm mode="Signup" /> 
      {/* SignupForm receives "Signup" as the mode to render the signup form */}
      
      <AuthLink 
        text="Already have an account?" 
        href="/Signin" 
        signinup="Signin" 
        classname="mt-8" 
      />
      {/* AuthLink used to navigate the user to the Signin page with a message */}
    </div>
  );
};

export default Signup;
