
import { Input } from "@/components/ui/input";
import Logo from "@/components/static/Logo";
import SectionTitle from "@/components/static/SectionTitle";
import SignupForm from "@/components/signup/SignupForm";
import AuthLink from "@/components/static/AuthLink";

export const metadata = {
  title: 'TieBreaker | signup',
  description: 'Generated by Next.js',
}


type Props={

}

const Signup = (props: Props) => {

  return (

      <div>
      <SectionTitle classname="mt-20  mb-5" text="Sign up, let's eat!"/>
      <SignupForm/>
      <AuthLink/>
      
    </div>
    
    
  );
}

export default Signup;
