# name: CI Pipeline

# on:
#   push:
#     branches:
#       - "*"  # All branches
#   pull_request:
#     branches:
#       - main
#       - test2  # Additional branches can be specified
#   workflow_dispatch:
#     inputs:
#       reason:
#         description: "Reason for triggering the workflow"

# jobs:
#   build:
#     name: Build and Test
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [20.x]

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "npm"

#       - name: Install dependencies
#         run: npm install

#       - name: Build the project
#         # Inject environment variables (secrets) into the build process
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
#           NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
#           SUPABASE_URL_DEV: ${{ secrets.SUPABASE_URL_DEV }}
#           SUPABASE_KEY_DEV: ${{ secrets.SUPABASE_KEY_DEV }}
#           SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD }}
#           SUPABASE_KEY_PROD: ${{ secrets.SUPABASE_KEY_PROD }}
#           DATABASE_URL_DEV: ${{ secrets.DATABASE_URL_DEV }}
#           DATABASE_URL_PROD: ${{ secrets.DATABASE_URL_PROD }}
#         run: npm run build

#       - name: Run Jest tests
#         env:
#           NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
#           NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
#           SUPABASE_URL_DEV: ${{ secrets.SUPABASE_URL_DEV }}
#           SUPABASE_KEY_DEV: ${{ secrets.SUPABASE_KEY_DEV }}
#           SUPABASE_URL_PROD: ${{ secrets.SUPABASE_URL_PROD }}
#           SUPABASE_KEY_PROD: ${{ secrets.SUPABASE_KEY_PROD }}
#           DATABASE_URL_DEV: ${{ secrets.DATABASE_URL_DEV }}
#           DATABASE_URL_PROD: ${{ secrets.DATABASE_URL_PROD }}
#         run: npm run test -- --coverage

#       - name: Upload Jest coverage report
#         uses: actions/upload-artifact@v3
#         with:
#           name: jest-coverage-report
#           path: coverage
