name: Test Project

on:
    pull_request:
        branches:
            -main
    push:
        branches:
            -CI-pipeline-test

jobs:
    test:
        runs-on: ubuntu-lates
        container:
            image: node:20
        steps:
            - uses: actions/checkout@v3
              with:
                node-version: 20
            - run: npm ci
            # - run: npm test
            - run: npm run dev