name: CI Pipeline

on:
  pull_request:
    branches:
      - "*" # Trigger on all PRs
  push:
    branches:
      - "*" # Trigger on pushes to the main branch

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      node-version: "20"
      run-lint: true
      run-prettier: true
      run-jest: true
